version: "3.7"

services:
  nanosp:
    image: ghcr.io/blooo-io/speculos:latest
    volumes:
      - ./bin:/speculos/apps
      - ./src:/speculos/sources
      - ./libsol:/speculos/libsol
    ports:
      - "5000:5000" # api
      - "40000:40000" # apdu
    environment:
      - GDB_DIRECTORY_LIST="/speculos/sources:/speculos/libsol"
    command: "-d --model nanosp apps/app.elf --display headless --apdu-port 40000 "
    # Add `--vnc-password "<password>"` for macos users to use built-in vnc client.
